name: Run Backend Tests

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5439:5432
        env:
          POSTGRES_DB: db
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..15}; do
            nc -z localhost 5439 && echo "Postgres is up!" && break
            echo "Waiting for Postgres..." && sleep 2
          done

      - name: Run tests with Maven
        run: mvn clean test
